### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by terralillo** [itsmepvr/anki-find-and-replace-in-templates#8]
Thanks for your job. I always get this error, why?

Información de depuración:
Anki 2.1.55 (01caec2a) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-28 12:03:09

Caught exception:
Traceback (most recent call last):
  File "C:\Users\fegar\AppData\Roaming\Anki2\addons21\992153575\findAndReplaceInTemplates.py", line 140, in findAndReplace
    ankimodels.update_dict(model)
  File "anki.models", line 223, in update_dict
  File "anki._backend_generated", line 883, in update_notetype_legacy
  File "anki._backend", line 148, in _run_command
anki.errors.CardTypeError: La plantilla de tarjeta ?1? tiene un problema.<br>Consulte la vista previa para obtener más información.

**Comment by itsmepvr** [comment]
I just checked the addon in Anki 2.1.55 and I see no issue. It might be some error with card template. Can you share what you are trying to do exactly before the error.
